name: Winnipeg Air Quality Django App deployment

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        name: Deploying to Github Pages
        runs-on: ubuntu-latest
        concurrency:
            group: "pages"
            cancel-in-progress: false
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        env:
            BUILD_PATH_PREFIX: ${{ github.event.repository.name }}

        steps:

            - name: Checking out the Code
              uses: actions/checkout@v4

            - name: Setting up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install deps
              run: |
                python3 -m venv env
                source env/bin/activate
                pip3 install -r requirements.txt
            
            - name: Navigate to the directory with manage.py
              run: cd wpgair  

            - name: Collect static files
              run: |
                source env/bin/activate
                cd wpgair
                python3 manage.py collectstatic --noinput
 
            # - name: Upload static files to GitHub Pages
            #   uses: actions/upload-pages-artifact@v3
            #   with:
            #     path: ./wpgair/static

            - name: Build static HTML (if necessary)
              run: |
                mkdir build
                cp wpgair/core/templates/core/index.html build/index.html  # Corrected path
                cp -r wpgair/static build/static 
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              