name: Django deployment

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        name: Deploying to Github Pages
        runs-on: ubuntu-latest
        concurrency:
            group: "pages"
            cancel-in-progress: false
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        env:
            BUILD_PATH_PREFIX: ${{ github.event.repository.name }}

        steps:
            # 1
            - name: Checking out the Code
              uses: actions/checkout@v4
            # 2
            - name: Setting up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            # 3
            - name: Install deps
              run: |
                python3 -m venv env
                source env/bin/activate
                pip3 install -r requirements.txt
            # 4
            # Step 4: Navigate to the directory where manage.py is located
            - name: Navigate to the directory with manage.py
              run: cd wpgair/wpgair  # Navigate to the correct folder

            - name: Collect static files
              run: |
                source env/bin/activate
                cd wpgair/wpgair
                python3 manage.py collecstatic --noinput
            # Step 5: Upload the static files to GitHub Pages
            - name: Upload static files to GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./wpgair/wpgair/static

            # Step 6: Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
